config/urls.py
from django.conf.urls.static import static
from config import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('kfc.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

kfc/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('product/<slug:product_slug>/', Product.as_view(), name='product'),
]

kfc/models.py
from django.db import models
from django.urls import reverse

class Products(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, db_index=True, max_length=255)
    price = models.CharField(max_length=255)
    photo = models.ImageField(upload_to="photos/%Y/%m/%d/")
    time_create = models.DateTimeField(auto_now_add=True)
    time_update = models.DateTimeField(auto_now=True)
    cat = models.ForeignKey('Category', on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product', kwargs={'product_slug': self.slug})

class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(unique=True, db_index=True, max_length=255)

    def __str__(self):
        return self.name

kfc/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import *


class Home(ListView):
    model = Products
    template_name = 'kfc/home.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        cats = Category.objects.all()
        products = Products.objects.all()
        context['cats'] = cats
        context['pros'] = products
        return context


class Product(DetailView):
    model = Products
    template_name = 'kfc/product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['name'] = context['product']
        cats = Category.objects.all()
        products = Products.objects.all()
        context['cats'] = cats
        context['pros'] = products
        return context

kfc/templates/kfc/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'kfc/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'kfc/css/styles.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'kfc/images/kfc-logo.jpg' %}" type="image/x-icon"/>
    <title>{{ name }}</title>
</head>
<body>
{% block mainmenu %}
<header>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <img src="{% static 'kfc/images/kfc-logo.jpg' %}" class="img-fluid logo" style="max-width: 100px">
            </div>
            <div class="cats mt-5" style="display: flex; justify-content: center;">
                {% for c in cats %}
                    <div class="cat d-none d-lg-block">
                        <a href="#" class="cat text-uppercase text-decoration-none"
                           style="color: #dd3333">{{ c.name }}</a>
                    </div>

                {% endfor %}
{% endblock %}
{% block info %}
            </div>
            <div class="col-12 text-center">
                <h2 class="text-uppercase mt-4">KFC / КФС</h2>
            </div>
            <div class="col-12 text-center">
                <h2 class="text-uppercase mt-4" style="color: red">БЕСПЛАТНАЯ ДОСТАВКА</h2>
            </div>
            <div class="col-12 text-center">
                <h2 class="mt-4" style="color: red">в Ташкенте</h2>
            </div>
            <div class="col-12 text-center mt-4 mb-3">
                <b>Наша служба доставки работает для Вас ежедневно с 09:00 и до 03:00.</b>
            </div>
        </div>
    </div>
{% endblock %}
</header>


{% for c in cats %}
    {% if c.products_set.exists %}

        <section style="background-color: #ffffff">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <h2 class="text-center mt-3 mb-4" style="color: red">
                            {{ c.name }}
                        </h2>
                    </div>
                </div>
            </div>
        </section>

        <section style="background-color: #f7f6f5">
            <div class="container">
                <div class="row">
                    {% for p in pros %}
                        {% if p.cat_id == c.pk %}
                            <div class="col-xl-3 col-sm-6 mt-5 mb-5 text-center align-items-center pro-card">
                                <img src="{{ p.photo.url }}" class="pro-img">
                                <div class="text-uppercase pt-3 pro-cont" style="font-size: x-small; ">{{ p.cat }}</div>
                                <div style="font-size: medium" class="pro-cont"><a class="text-decoration-none" style="color: black" href="/product/{{ p.slug }}">{{ p.name }}</a></div>
                                <div class="pb-3"><b>{{ p.price }} UZS</b></div>
                                <div class="btn-basket text-center text-uppercase">

                                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
                                         class="bi bi-bag-check" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd"
                                              d="M10.854 8.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 0 1 .708-.708L7.5 10.793l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                                        <path d="M8 1a2.5 2.5 0 0 1 2.5 2.5V4h-5v-.5A2.5 2.5 0 0 1 8 1zm3.5 3v-.5a3.5 3.5 0 1 0-7 0V4H1v10a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V4h-3.5zM2 5h12v9a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V5z"/>
                                    </svg>

                                    В корзину

                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                </div>
            </div>

        </section>

    {% endif %}
{% endfor %}

<footer style="margin-bottom: 200px">

</footer>
    </div>
<script src="{% static 'kfc/js/bootstrap.bundle.js' %}"></script>
</body>
</html>

kfc/templates/kfc/product.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'kfc/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'kfc/css/styles.css' %}"/>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@500&display=swap" rel="stylesheet">
    <link rel="shortcut icon" href="{% static 'kfc/images/kfc-logo.jpg' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"/>
    <title>{{ name }}</title>
</head>
<body>
<header>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 text-center">
                <a href="/"><img src="{% static 'kfc/images/kfc-logo.jpg' %}" class="img-fluid logo" style="max-width: 100px"></a>
            </div>
            <div class="cats mt-5" style="display: flex; justify-content: center;">
                {% for c in cats %}
                    <div class="cat d-none d-lg-block">
                        <a href="#" class="cat text-uppercase text-decoration-none"
                           style="color: #dd3333">{{ c.name }}</a>
                    </div>

                {% endfor %}

            </div>
        </div>
    </div>
</header>

<section>
    <div class="container" style="font-family: 'Oswald', sans-serif">
        <div class="row">
            <div class="col-xl-4 col-sm-12 text-start">
                <img src="{{ product.photo.url }}" style="border: 1px solid #b4b1ad; height: 314px;width: 448.578px">
            </div>
            <div class="col-xl-6 col-sm-12" style="padding-left: 60px">
                <h2 style="font-size: 1.875rem;line-height: 1.2;color: #222529;letter-spacing: -0.01em;font-weight: 700; font-family: sans-serif; margin-bottom: 20px">{{ product.name }}</h2>

                <div class="rating">
                    <input type="radio" name="star" id="star1"><label for="star1"></label>
                    <input type="radio" name="star" id="star2"><label for="star2"></label>
                    <input type="radio" name="star" id="star3"><label for="star3"></label>
                    <input type="radio" name="star" id="star4"><label for="star4"></label>
                    <input type="radio" name="star" id="star5"><label style="margin-right: 2px" for="star5"></label>
                </div>
                <hr style="margin-top: 50px; width: 223px">
                <p style="margin-bottom: 20px; font-size: x-large; margin-top: 22px"><b>{{ product.price }} UZS</b></p>
                <p style="font-size: small"><span style="color: #b4b1ad">КАТЕГОРИЯ:</span> <b>{{ product.cat }}</b></p>
            </div>
        </div>
    </div>
</section>

<script src="{% static 'kfc/js/bootstrap.bundle.js' %}"></script>
</body>
</html>